# .travis.yml file

language: r
cache: packages
warnings_are_errors: true
sudo: false

before_install:
  - Rscript -e 'install.packages("nlme", lib="/home/travis/R-bin/lib/R/library/")'

env:
 global:
   - CRAN: http://cran.rstudio.com

notifications:
  email:
    on_success: change
    on_failure: change
